
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('STN','Londono Stanstedo oro uostas','Londonas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SOU','Sautamptono oro uostas','Sautamptonas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('NWI','Noridžo tarptautinis oro uostas','Noridžas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('NCL','Niukaslio oro uostas','Niukaslas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MHZ','RAF Mildenhall','Mildenhall','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MAN','Mančesterio oro uostas','Mančesteris','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LTN','Londono Lutono oro uostas','Londonas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LPL','Liverpulio Johno Lennono oro uostas','Liverpulis','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LKZ','RAF Lakenheath','Lakenheath','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LHR','Londono Hitrou oro uostas','Londonas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LGW','Londono Getviko oro uostas','Londonas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LBA','Lydso Bradfordo oro uostas','Lidsas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GLA','Glazgo tarptautinis oro uostas','Glazgas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FFD','RAF Fairford','Fairford','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('EXT','Ekseterio tarptautinis oro uostas','Ekseteris','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('EMA','Rytų Midlandso oro uostas','Notingemas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('EDI','Edinburgo oro uostas','Edinburgas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DSA','Robino Hudo Donkasterio Šefildo oro uostas','Donkasteris','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CWL','Kardifo tarptautinis oro uostas','Kardifas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BZZ','RAF Brize Norton','Brize Norton','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BRS','Bristolio oro uostas','Bristolis','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BOH','Bornmuto oro uostas','Bornmutas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BHX','Birmingemo tarptautinis oro uostas','Birmingamas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BHD','George geriausias Belfasto miesto oro uostas','Belfastas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BFS','Belfasto tarptautinis oro uostas','Belfastas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('AKT','RAF Akrotiri','Akrotiri','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ABZ','Aberdeen Dyce oro uostas','Aberdynas','Jungtinė Karalystė');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SIP','Simferopolio tarptautinis oro uostas','Simferopolis','Ukraina');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ODS','Odesos tarptautinis oro uostas','Odesa','Ukraina');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KBP','Boryspilio tarptautinis oro uostas','Kijevas','Ukraina');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('HRK','Charkovo tarptautinis oro uostas','Charkovas','Ukraina');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('EIN','Eindhoveno oro uostas','Eindhovenas','Nyderlandai');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('AMS','Amsterdamo oro uostas Schiphol','Amsterdamas','Olandija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ZRH','Ciuricho oro uostas','Ciurichas','Šveicarija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GVA','Ženevos oro uostas','Ženeva','Šveicarija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MMX','Malmės oro uostas','Malmė','Švedija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LLA','Luleå oro uostas','Luleå','Švedija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GOT','Geteborgo-Landvetterio oro uostas','Geteborgas','Švedija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ARN','Stokholmo Arlandos oro uostas','Stokholmas','Švedija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TFS','Tenerifės pietinis oro uostas','Tenerifės sala','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TFN','Šiaurės Tenerifės oro uostas','Tenerifės sala','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SPC','La Palmos oro uostas','Sta Cruz de la Palma La Palmos sala','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SCQ','Santiago de Compostela oro uostas','Santiago de Compostela','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PMI','Palmos de Maljorkos oro uostas','Maljorkos Palma','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MAD','Adolfo Suárez Madridas – Barajas oro uostas','Madridas','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LPA','Gran Kanarijos oro uostas','Gran Kanarijos sala','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BCN','Barselonos – El Prato oro uostas','Barselona','​​Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ALC','Alikantės tarptautinis oro uostas','Alikantė','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('AGP','Malagos oro uostas','Malaga','Ispanija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LJU','Liublianos Jože Pučnik oro uostas','Liubliana','Slovėnija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BTS','Bratislavos oro uostas','Bratislava','Slovakija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BEG','Belgrado Nikola Tesla oro uostas','Belgradas','Serbija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ZIA','Žukovskio tarptautinis oro uostas','Maskva','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VKO','Vnukovo tarptautinis oro uostas','Maskva','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('UFA','Ufos tarptautinis oro uostas','Ufa','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SVO','Šeremetjevo tarptautinis oro uostas','Maskva','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ROV','Platovo tarptautinis oro uostas','Rostovas prie Dono','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LED','Pulkovo oro uostas','Šv. Peterburgas','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KZN','Kazanės tarptautinis oro uostas','Kazanė','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KUF','tarptautinis Kurumocho oro uostas','Samara','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KJA','Jemeljanovo oro uostas','Krasnojarskas','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GRV','Šiaurės Grozno oro uostas','Groznas','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DME','Domodedovo tarptautinis oro uostas','Maskva','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('AER','Sočio tarptautinis oro uostas','Sočis','Rusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('OTP','Bukarešto tarptautinis Henri Coandă oro uostas','Bukareštas','Rumunija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TER','Lajeso oro uostas','Praia da Vitória','Portugalija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PDL','João Paulo II oro uostas','Ponta Delgada','Portugalija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('OPO','Francisco de Sá Carneiro oro uostas','Porto','Portugalija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LIS','Humberto Delgado oro uostas (Lisabonos Portela oro uostas)','Lisabona','Portugalija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FAO','Faro oro uostas','Faro','Portugalija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('WRO','Koperniko oro uostas Vroclavas','Vroclavas','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('WMI','Modlino oro uostas','Varšuva','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('WAW','Varšuvos Šopeno oro uostas','Varšuva','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('POZ','Poznanės-Ławica oro uostas','Poznanė','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KTW','Katovicų tarptautinis oro uostas','Katovicai','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KRK','Krokuvos Jono Pauliaus II tarptautinis oro uostas','Krokuva','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GDN','Gdansko Lecho Valensos oro uostas','Gdanskas','Lenkija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TRD','Trondheimo oro uostas Værnes','Trondheimas','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TOS','Trumsės oro uostas','Trumsė','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SVG','Stavangerio oro uostas Sola','Stavangeris','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('OSL','Oslo Gardermoen oro uostas','Oslas','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BOO','Bodø oro uostas','Bodø','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BGO','Bergeno oro uostas Fleslandas','Bergenas','Norvegija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TGD','Podgoricos oro uostas','Podgorica','Juodkalnija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MLA','Maltos tarptautinis oro uostas','Valeta','Malta');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SKP','Skopjės Didžiojo oro uostas','Skopjė','Makedonija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LUX','Liuksemburgo-Findelio tarptautinis oro uostas','Liuksemburgas','Liuksemburgas');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VNO','Vilniaus tarptautinis oro uostas','Vilnius','Lietuva');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('RIX','Rygos tarptautinis oro uostas','Ryga','Latvija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PRN','Prištinos tarptautinis oro uostas','Priština','Kosovas');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VRN','Veronos Villafranca oro uostas','Verona','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VCE','Venecijos Marco Polo oro uostas','Venecija','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TSF','Treviso-Sant Angelo oro uostas','Trevizas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TRN','Turino oro uostas','Torinas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PSA','Pizos tarptautinis oro uostas','Piza','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PMO','Falcone – Borsellino oro uostas','Palermas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('NAP','Neapolio tarptautinis oro uostas','Napolis','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MXP','Malpensa tarptautinis oro uostas','Milanas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LIN','Milano Linate oro uostas','Milanas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('GOA','Genujos Cristoforo Colombo oro uostas','Genova','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FCO','Roma – Fiumicino tarptautinis oro uostas Leonardo da Vinci','Roma','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CTA','Katanijos-Fontanarosos oro uostas','Katanija','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CŽV','Roma – Ciampino tarptautinis oro uostas G. B. Pastine','Roma','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CAG','Kaljario Elmaso oro uostas','Kaljaris','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BRI','Bario Karolio Wojtyłos oro uostas','Baris','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BLQ','Bolonijos Guglielmo Marconi oro uostas','Bolonija','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BGY','Il Caravaggio tarptautinis oro uostas','Bergamas','Italija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SNN','Šanono oro uostas','Šanonas','Airija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ORK','Korko oro uostas','Korkas','Airija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DUB','Dublino oro uostas','Dublinas','Airija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('KEF','Keflaviko tarptautinis oro uostas','Reikjavikas','Islandija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BUD','Budapešto Liszto Ferenco tarptautinis oro uostas','Budapeštas','Vengrija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SKG','Salonikų Makedonijos tarptautinis oro uostas','Salonikai','Graikija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('HER','Herakliono tarptautinis Nikos Kazantzakis oro uostas','Heraklionas','Graikija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ATH','Atėnų tarptautinis oro uostas Eleftherios Venizelos','Atėnai','Graikija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TXL','Berlyno-Tėgelio oro uostas','Berlynas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SXF','Berlyno-Šionefeldo oro uostas','Berlynas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('STR','Štutgarto oro uostas','Štutgartas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('RMS','Ramstein oro bazė','Ramstein','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('NUE','Niurnbergo oro uostas','Niurnbergas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MUC','Miuncheno oro uostas','Miunchenas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LEJ','Leipcigo / Halės oro uostas','Leipcigas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('HAM','Hamburgo oro uostas','Hamburgas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('HAJ','Hanoverio oro uostas','Hanoveris','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FRA','Frankfurto prie Maino oro uostas','Frankfurtas prie Maino','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FMO','Miunsterio Osnabriuko oro uostas','Miunsteris','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('FKB','Karlsruhe Baden-Baden oro uostas','Baden-Baden','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DUS','Diuseldorfo oro uostas','Diuseldorfas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DTM','Dortmundo oro uostas','Dortmundas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('DRS','Drezdeno oro uostas','Drezdenas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CGN','Kelno Bonos oro uostas','Kelnas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BRE','Brėmeno oro uostas','Brėmenas','Vokietija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TLS','Tulūzos-Blanjako oro uostas','Tulūza / Blanjakas','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ORY','Paryžiaus-Orli oro uostas','Paryžius','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('NCE','Nicos – Žydrosios pakrantės oro uostas','Nica','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MRS','Marselio Provanso oro uostas','Marselis','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LYS','Liono Saint-Exupéry oro uostas','Lionas','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CDG','Paryžiaus-Šarlio de Golio oro uostas','Paryžius','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BSL','EuroAirport Basel-Mulhouse-Freiburg Airport','Bale / Mulhouse','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BOD','Bordo-Merignac oro uostas','Bordo','Prancūzija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('HEL','Helsinkio Vantos oro uostas','Helsinkis','Suomija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TLL','Talino oro uostas','Talinas','Estija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CPH','Kopenhagos Kastrupo oro uostas','Kopenhaga','Danija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BLL','Bilundo oro uostas','Bilundas','Danija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('AAL','Olborgo oro uostas','Olborgas','Danija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('PRG','Prahos Václavo Havelo oro uostas','Praha','Čekija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('ZAG','Zagrebo oro uostas','Zagrebas','Kroatija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VAR','Varnos oro uostas','Varna','Bulgarija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SOF','Sofijos oro uostas','Sofija','Bulgarija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BOJ','Burgaso oro uostas','Burgasas','Bulgarija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('SJJ','Sarajevo tarptautinis oro uostas','Sarajevas','Bosnija ir Hercegovina');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('LGG','Lježo oro uostas','Lježas','Belgija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('CRL','Briuselio Pietų Šarlerua oro uostas','Briuselis','Belgija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('BRU','Briuselio oro uostas','Briuselis','Belgija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('MSQ','Minsko nacionalinis oro uostas','Minskas','Baltarusija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('VIE','Vienos tarptautinis oro uostas','Viena','Austrija');
INSERT INTO Airports(IATA,Name,City,Country) VALUES ('TIA','Tiranos tarptautinis oro uostas Motina Teresė','Tirana','Albanija');
